kind: Service
apiVersion: v1
metadata:
  name: go-write
  labels:
    app: go-write
spec:
  selector:
    app: go-write
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-write
  labels:
    app: go-write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-write
  template:
    metadata:
      labels:
        app: go-write
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "go-write"
        dapr.io/port: "8080"
    spec:
      containers:
      - name: go-write
        image: tens/go-write
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
